server:
  port: 3344

spring:
  application:
    name:  cloud-config-center  #注册进consul注册中心的微服务名字


  cloud:

    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}


    config:
      server:
        git:
          uri: https://gitee.com/syning310/springcloud-config.git   # gitee上的仓库地址
          ####搜索目录
          search-paths:
            - springcloud-config

          username: Syning310
          password: shangyining0310


      ####读取分支
      label: main


  # rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'   # 暴露所有节点








