server:
  port: 8006
#  port: 8007

spring:
  application:
    name: consul-provider-payment

  zipkin: #<-------------------------------------关键
    base-url: http://localhost:9411
    sleuth: #<-------------------------------------关键
      sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集
      probability: 1


# consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:

        # hostname: 127.0.0.1
        service-name: ${spring.application.name}

