server:
  port: 8100
#  port: 8200

spring:
  application:
    name: provider-hystrix-payment

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}


