server:
  port: 8401

spring:
  application:
    name: alibaba-sentinel-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   # nacos服务注册中心地址

    sentinel:
      transport:
        dashboard: localhost:8080     # 配置sentinel dashboard地址

        port: 8719    # 默认8719端口，假如被占用则会自动从8719开始依次+1扫描，直至找到未被占用的端口

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持

