server:
  port: 20000

spring:
  application:
    name: seata-order-service

  cloud:
    alibaba:
      seata:
        # 自定义事务组需要与seata-server中的对应
        tx-service-group: xia_tx_group


    nacos:
      discovery:
        server-addr: localhost:8848

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: syning

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
