server:
  port: 21000

spring:
  application:
    name: seata-storage-service

  cloud:
    alibaba:
      seata:
        tx-service-group: xia_tx_group

    nacos:
      discovery:
        server-addr: localhost:8848

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage
    username: root
    password: syning

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


